/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PWM_BUCK.h>
#include <Clock_1.h>
#include <PWM_UNFOLD_A.h>
#include <PWM_UNFOLD_B.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <Pin_5_aliases.h>
#include <Pin_5.h>
#include <Pin_6_aliases.h>
#include <Pin_6.h>
#include <ADC_DelSig_1.h>
#include <ADC_SAR_2.h>
#include <Pin_7_aliases.h>
#include <Pin_7.h>
#include <Pin_8_aliases.h>
#include <Pin_8.h>
#include <Pin_9_aliases.h>
#include <Pin_9.h>
#include <Pin_10_aliases.h>
#include <Pin_10.h>
#include <ADC_SAR_1.h>
#include <LCD_Char_1.h>
#include <ADC_DelSig_1_theACLK.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_SAR_2_IRQ.h>
#include <ADC_SAR_2_theACLK.h>
#include <ADC_SAR_2_Bypass_aliases.h>
#include <ADC_SAR_2_Bypass.h>
#include <ADC_SAR_1_IRQ.h>
#include <ADC_SAR_1_theACLK.h>
#include <ADC_SAR_1_Bypass_aliases.h>
#include <ADC_SAR_1_Bypass.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

