/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <PWM_BUCK.h>
#include <Clock_1.h>
#include <PWM_UNFOLD_A.h>
#include <PWM_UNFOLD_B.h>
#include <BUCK_LS_aliases.h>
#include <BUCK_LS.h>
#include <A_HS_aliases.h>
#include <A_HS.h>
#include <A_LS_aliases.h>
#include <A_LS.h>
#include <B_HS_aliases.h>
#include <B_HS.h>
#include <B_LS_aliases.h>
#include <B_LS.h>
#include <ADC_DelSig_V.h>
#include <ADC_SAR_2.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <V_SENSE_aliases.h>
#include <V_SENSE.h>
#include <Pin_10_aliases.h>
#include <Pin_10.h>
#include <ADC_SAR_V.h>
#include <LCD_Char_1.h>
#include <Clock_2.h>
#include <UART_1.h>
#include <SS_aliases.h>
#include <SS.h>
#include <SCLK_aliases.h>
#include <SCLK.h>
#include <MOSI_aliases.h>
#include <MOSI.h>
#include <MISO_aliases.h>
#include <MISO.h>
#include <SPIS_1.h>
#include <Clock_3.h>
#include <BUCK_HS_aliases.h>
#include <BUCK_HS.h>
#include <ADC_DelSig_V_theACLK.h>
#include <ADC_DelSig_V_Ext_CP_Clk.h>
#include <ADC_DelSig_V_AMux.h>
#include <ADC_SAR_2_IRQ.h>
#include <ADC_SAR_2_theACLK.h>
#include <ADC_SAR_2_Bypass_aliases.h>
#include <ADC_SAR_2_Bypass.h>
#include <ADC_SAR_V_IRQ.h>
#include <ADC_SAR_V_theACLK.h>
#include <ADC_SAR_V_Bypass_aliases.h>
#include <ADC_SAR_V_Bypass.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <UART_1_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

